# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    env_file: ".env.production"
    volumes:
      - ./:/app
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.prod.ini:ro
   
